"""add discovered_from column to papers

Revision ID: 95900fcda75f
Revises: 95564679b92f
Create Date: 2026-06-15 11:36:50.721731

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '95900fcda75f'
down_revision: Union[str, None] = '95564679b92f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('discovered_from', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'discovered_from')
    # ### end Alembic commands ###
