"""add abstract column to papers

Revision ID: 95564679b92f
Revises: 0001
Create Date: 2026-06-15 10:35:13.900160

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '95564679b92f'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('abstract', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'abstract')
    # ### end Alembic commands ###
